Attempt to apply a classifier into the data.

In [1]:
import os
try:
	os.chdir(os.path.join(os.getcwd(), 'assignment_2'))
	print(os.getcwd())
except:
	pass

/Users/nwoodle/Developer/CSE258_recommender_system/assignment_2

In [2]:
import numpy as np 
import pandas as pd 
import pprint

pp = pprint.PrettyPrinter(indent=4)

In [3]:
# Data Preprocessing
closed_data = pd.read_csv("closed_data.csv")
closed_data = closed_data.loc[closed_data["district"].isin([1,2,3,4,5,6,7,8,9])]
print(f"Dataset size is {len(closed_data)}.")

Dataset size is 125177.

In [4]:
# Select columns
'''
Preprocessing:
	- Keep only closed case
	- Keep case with district data

Features:
	- Service name: service_name, onehot
	- Total population: total_pop2017
	- White population: white_pop2017
	- African American population: afram_pop2017
	- Hispanic population population: hisp_pop2017
	- Case origion: case_origin, onehot
	- Description sentiment: feature sentiment analysis, homebrewed
        - neg, neu, com, pos
    - Average income: avg_agi
    - District: disctirct, onehot
'''
column_lst = ["total_pop2017", "white_pop2017", "afram_pop2017", "hisp_pop2017",\
              "avg_agi", "neg", "neu", "com", "pos"]
onehot_lst = ["service_name", "case_origin", "district"]
prep_data = closed_data[column_lst]

In [17]:
# Onehot Process
onehot_data = closed_data[onehot_lst].astype("str")
categorize_data = pd.get_dummies(onehot_data, prefix=onehot_lst)
dataset = pd.concat([prep_data, categorize_data], axis=1)

,service_name_--Select Answer--,service_name_72 Hour Violation,service_name_ACTUATOR EQUIPMENT FAILURE,service_name_ADMIN - Referral ReReferral,service_name_AVA,service_name_BICYCLE - TEO - Bicycle Facility Path,service_name_BICYCLE - TEO - Bicycle Facility Racks,service_name_Bicycle Facility Maintenance,service_name_Bicycle Removal,service_name_Bridge Maintenance,...,case_origin_nan,district_1.0,district_2.0,district_3.0,district_4.0,district_5.0,district_6.0,district_7.0,district_8.0,district_9.0
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125172,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
125173,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
125174,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
125175,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
125176,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0